### ISSUE TITLE
Terrific plugin. Any way to make this compatible with Eminiarts/Nova-Tabs?

### ISSUE THREAD

**Issue by MikeCraig418** [SpiritSaint/nova-gridder#1]
A grid inside of a tab would be.... dare I say? EPIC

See https://github.com/eminiarts/nova-tabs

**Comment by Zen0x7** [comment]
I'll try 👍

**Comment by Zen0x7** [comment]
@949mac 

Well, after an investigation I understood that this package acts only on a Panel. Nova-tabs has its own component that extends the behavior of the Panel. If I overwrite it, every time an update of the other package is performed it could break the functionality of Nova-tabs. To solve this I suggested a non breacking change in their repository allowing the support of this package. The progress of this issue will depend on whether they are willing to accept the change, in other cases i have rejected changes because the maintainer do not want to support 3rd parties packages.

**Comment by MikeCraig418** [comment]
Thanks for looking!

**Comment by MikeCraig418** [comment]
I just looked at your pull request. It looks great and is a terrific contribution. Fingers crossed.

**Comment by Zen0x7** [comment]
@949mac well, the change still stuck. But I need this feature in my proyect too. Ill try to code some non-breaking solution from here.

**Comment by Zen0x7** [comment]
@949mac 

Until the official repository does not make a decision, I recommend using my fork available at https://packagist.org/packages/demency/nova-tabs. It's nova-gridder compatible. I created because nova-tabs can't be using local nova installation.
